# This Software (Dioptra) is being made available as a public service by the
# National Institute of Standards and Technology (NIST), an Agency of the United
# States Department of Commerce. This software was developed in part by employees of
# NIST and in part by NIST contractors. Copyright in portions of this software that
# were developed by NIST contractors has been licensed or assigned to NIST. Pursuant
# to Title 17 United States Code Section 105, works of NIST employees are not
# subject to copyright protection in the United States. However, NIST may hold
# international copyright in software created by its employees and domestic
# copyright (or licensing rights) in portions of software that were assigned or
# licensed to NIST. To the extent that NIST holds copyright in this software, it is
# being made available under the Creative Commons Attribution 4.0 International
# license (CC BY 4.0). The disclaimers of the CC BY 4.0 license apply to all parts
# of the software developed or licensed by NIST.
#
# ACCESS THE FULL CC BY 4.0 LICENSE HERE:
# https://creativecommons.org/licenses/by/4.0/legalcode
name: dioptra
channels:
  - defaults
dependencies:
  - bottleneck
  - click>=7.1.0,<8 # mlflow/prefect requirement
  - cloudpickle>=1.3.0 # prefect requirement
  - cython
  - dask>=2021.06.0 # prefect requirement
  - docker-py>=4.0.0 # mlflow requirement
  - entrypoints # mlflow requirement
  - gitpython>=2.1.0 # mlflow requirement
  - gunicorn # mlflow requirement
  - h5py=2.10.0 # tensorflow requirement
  - jinja2>=2.10.1,<3.0
  - joblib
  - markupsafe<=2.0.1
  - matplotlib
  - mkl
  - nose
  - numexpr
  - numpy>=1.22.0
  - packaging # mlflow requirement
  - pandas>=1.1.1 # mlflow/prefect requirement
  - pillow
  - pip
  - protobuf>=3.7.0 # mlflow requirement
  - psutil
  - psycopg2
  - pycodestyle
  - pytables
  - python-dateutil>=2.8.0 # prefect requirement
  - python
  - pytz>=2018.7 # mlflow requirement
  - pyyaml>=5.1 # mlflow requirement
  - redis-py>=3.5.0 # prefect requirement
  - requests>=2.25 # prefect requirement
  - scipy>=1.4.1 # adversarial-robustness-toolbox requirement
  - scikit-learn
  - simplejson
  - six>=1.13.0 # adversarial-robustness-toolbox requirement
  - sqlalchemy>=1.3.0,<2 # mlflow requirement
  - sqlparse>=0.3.1 # mlflow requirement
  - werkzeug>=1.0.0,<2
  - pip:
      - adversarial-robustness-toolbox
      - alembic<2.0.0
      - boto3>=1.16.0 # mlflow requirement
      - databricks-cli>=0.8.7 # mlflow requirement
      - flask-accepts>=0.17.0,<1
      - Flask-Injector>=0.12.0,<1
      - Flask-Migrate>=2.5.0,<3
      - flask-restx>=0.2.0,<1
      - Flask-SQLAlchemy>=2.4.0,<3
      - Flask-WTF>=0.14.3,<1
      - Flask>=1.1.4,<2
      - gorilla
      - imgaug>=0.4.0,<1
      - marshmallow>=3.9.0,<4
      - mlflow
      - multimethod>=1.5
      - passlib
      - prefect
      - prometheus-flask-exporter # mlflow requirement
      - pyarrow>=2.0.0
      - pycocotools
      - python-json-logger>=2.0.0
      - querystring-parser # mlflow requirement
      - rich>=9.1.0
      - rq>=1.5.0
      - structlog>=20.2.0
      - tensorflow
      - typing-extensions>=3.7.4.3
