# This Software (Dioptra) is being made available as a public service by the
# National Institute of Standards and Technology (NIST), an Agency of the United
# States Department of Commerce. This software was developed in part by employees of
# NIST and in part by NIST contractors. Copyright in portions of this software that
# were developed by NIST contractors has been licensed or assigned to NIST. Pursuant
# to Title 17 United States Code Section 105, works of NIST employees are not
# subject to copyright protection in the United States. However, NIST may hold
# international copyright in software created by its employees and domestic
# copyright (or licensing rights) in portions of software that were assigned or
# licensed to NIST. To the extent that NIST holds copyright in this software, it is
# being made available under the Creative Commons Attribution 4.0 International
# license (CC BY 4.0). The disclaimers of the CC BY 4.0 license apply to all parts
# of the software developed or licensed by NIST.
#
# ACCESS THE FULL CC BY 4.0 LICENSE HERE:
# https://creativecommons.org/licenses/by/4.0/legalcode
name: securing-ai-testbed
channels:
  - defaults
dependencies:
  - autopep8
  - beautifulsoup4
  - blinker
  - bottleneck
  - click>=7.1.0,<8
  - cloudpickle
  - coverage
  - cryptography=3.*
  - cython
  - dask
  - docker-py>=4.0.0
  - docopt=0.6.*
  - docutils=0.16
  - entrypoints>=0.3
  - flake8>=3.8.0
  - gitpython
  - gunicorn
  - h5py
  - ipython
  - isort>=5.6.0
  - jedi=0.17.2 # Downgrade fixes IPython tab-completion error
  - jinja2
  - joblib
  - jupyter
  - markupsafe
  - matplotlib
  - networkx=2.4
  - nose
  - numexpr
  - numpy>=1.19.0
  - pandas>=1.1.0
  - parso=0.7.* # Downgrade fixes IPython tab-completion error
  - passlib
  - pillow
  - pip
  - protobuf
  - psutil
  - psycopg2
  - pycodestyle
  - pydocstyle
  - pymongo=3.11.*
  - pymysql
  - pyodbc
  - pytables
  - pytest>=6
  - python-dateutil
  - python-jsonrpc-server=0.3.*
  - python=3.8.*
  - pytz
  - pyyaml=5.3.*
  - pyzmq
  - redis-py>=3.5.0
  - requests=2.24.*
  - scipy=1.5.*
  - setuptools
  - simplejson
  - six
  - scikit-learn=0.23.*
  - sphinx>=3.3.0
  - toml=0.10.*
  - twine
  - ujson=1.35
  - watchdog=0.10.*
  - werkzeug>=1.0.0,<2
  - wheel
  - pip:
      - adversarial-robustness-toolbox==1.5.1
      - alembic<=1.4.1
      - black>=20.8b1
      - black[d]
      - boto3>=1.16.0
      - build
      - commitizen
      - databricks-cli
      - docformatter
      - fett~=0.3.2
      - flake8-bugbear
      - Flask>=1.1.0,<2
      - flask-accepts>=0.17.0,<1
      - Flask-Injector>=0.12.0,<1
      - Flask-JWT-Extended>3.24.0,<4
      - Flask-Migrate>=2.5.0,<3
      - flask-restx>=0.2.0,<1
      - Flask-SQLAlchemy>=2.4.0,<3
      - Flask-WTF>=0.14.0,<1
      - freezegun
      - gorilla
      - injector>=0.18.0
      - markdown
      - marshmallow>=3.9.0,<4
      - mlflow==1.12.1
      - mnist
      - multimethod>=1.5
      - mypy>=0.900
      - plantuml-markdown
      - pre-commit
      - prefect==0.14.*
      - prometheus-flask-exporter
      - pyarrow
      - pymdown-extensions
      - pytest-cov
      - pytest-datadir
      - pytest-testinfra
      - python-json-logger
      - querystring-parser
      - recommonmark
      - rich
      - rq>=1.5.0
      - rstcheck
      - seed-isort-config
      - snooty
      - snooty-lextudio
      - sphinx-autobuild
      - sphinx-autodoc-typehints
      - sphinx-book-theme
      - sphinx-copybutton
      - sphinx-panels
      - sphinx-rtd-theme
      - sphinx-togglebutton
      - sphinxcontrib-openapi
      - sqlalchemy-stubs
      - sqlalchemy==1.3.13
      - sqlparse
      - structlog>=20.2.0
      - tabulate
      - tox
      - types-click
      - types-cryptography
      - types-enum34
      - types-Flask
      - types-freezegun
      - types-ipaddress
      - types-Jinja2
      - types-python-dateutil
      - types-redis
      - types-Werkzeug
      - typing-extensions>=3.7.4.0
      - web-compile
