# This Software (Dioptra) is being made available as a public service by the
# National Institute of Standards and Technology (NIST), an Agency of the United
# States Department of Commerce. This software was developed in part by employees of
# NIST and in part by NIST contractors. Copyright in portions of this software that
# were developed by NIST contractors has been licensed or assigned to NIST. Pursuant
# to Title 17 United States Code Section 105, works of NIST employees are not
# subject to copyright protection in the United States. However, NIST may hold
# international copyright in software created by its employees and domestic
# copyright (or licensing rights) in portions of software that were assigned or
# licensed to NIST. To the extent that NIST holds copyright in this software, it is
# being made available under the Creative Commons Attribution 4.0 International
# license (CC BY 4.0). The disclaimers of the CC BY 4.0 license apply to all parts
# of the software developed or licensed by NIST.
#
# ACCESS THE FULL CC BY 4.0 LICENSE HERE:
# https://creativecommons.org/licenses/by/4.0/legalcode
name: securing-ai-testbed
channels:
  - defaults
dependencies:
  - autopep8
  - beautifulsoup4
  - blinker
  - bottleneck
  - chardet>=3.0.0,<4
  - click>=7.1.0,<8
  - cloudpickle>=1.3.0 # prefect requirement
  - coverage
  - cryptography=3.*
  - cython
  - dask>=2.17.0 # prefect requirement
  - docker-py>=4.0.0
  - docopt=0.6.*
  - docutils=0.16
  - entrypoints
  - flake8>=3.8.0
  - gitpython>=2.1.0 # mlflow requirement
  - gunicorn
  - h5py=2.10.0 # tensorflow requirement
  - ipython
  - isort>=5.6.0
  - jinja2>=2.11.0,<3
  - joblib
  - jupyter
  - markupsafe<=2.0.1
  - matplotlib
  - networkx
  - nose
  - numexpr
  - numpy>=1.18.0 # adversarial-robustness-toolbox requirement
  - packaging=20.* # mlflow requirement
  - pandas>=1.1.0
  - pillow
  - pip
  - protobuf>=3.7.0 # mlflow requirement
  - psutil
  - psycopg2
  - pymysql
  - pyodbc
  - pytables
  - pytest>=6,<7
  - python-dateutil>=2.8.0 # prefect requirement
  - python=3.9.*
  - pytz
  - pytz>=2018.7 # mlflow requirement
  - pyyaml=5.3.1 # mlflow requirement
  - pyzmq
  - redis-py>=3.2.1
  - requests>=2.25.0
  - scikit-learn>=1.0.0,<1.1.0
  - scipy>=1.4.1 # adversarial-robustness-toolbox requirement
  - setuptools
  - simplejson
  - six
  - sqlalchemy
  - sqlparse>=0.3.1 # mlflow requirement
  - toml
  - twine
  - urllib3>=1.26.0
  - watchdog=0.10.4
  - wheel
  - pip:
      - adversarial-robustness-toolbox==1.9.*
      - alembic<=1.4.1
      - black>=20.8b1,<22
      - boto3
      - build
      - commitizen
      - databricks-cli>=0.8.7 # mlflow requirement
      - docformatter
      - flake8-bugbear
      - flask-accepts>=0.17.0
      - Flask-Injector>=0.12.0
      - Flask-JWT-Extended>3.24.0
      - Flask-Migrate>=2.5.0
      - flask-restx>=0.2.0
      - Flask-SQLAlchemy>=2.4.0
      - Flask-WTF>=0.14.0
      - Flask>=1.1.4,<2
      - freezegun
      - gorilla
      - imgaug>=0.4.0
      - injector>=0.18.0
      - markdown
      - marshmallow>=3.9.0,<4
      - mlflow>=1.12.0,<2
      - multimethod>=1.5
      - mypy>=0.920
      - passlib
      - plantuml-markdown
      - pre-commit
      - prefect>=1.0.0
      - prometheus-flask-exporter
      - pyarrow
      - pycodestyle
      - pydocstyle
      - pymdown-extensions
      - pytest-cov
      - pytest-datadir
      - pytest-testinfra
      - python-json-logger>=2.0.0
      - querystring-parser
      - recommonmark
      - rich>=9.1.0
      - rq>=1.5.0
      - rstcheck
      - sphinx>=3.3.0
      - sphinx-autobuild
      - sphinx-autodoc-typehints
      - sphinx-book-theme
      - sphinx-copybutton
      - sphinx-panels
      - sphinx-rtd-theme
      - sphinx-togglebutton
      - sphinxcontrib-openapi
      - sqlalchemy-stubs
      - structlog>=20.2.0
      - tabulate
      - tox
      - types-click
      - types-cryptography
      - types-enum34
      - types-Flask
      - types-freezegun
      - types-ipaddress
      - types-Jinja2
      - types-python-dateutil
      - types-PyYAML
      - types-redis
      - types-requests
      - types-Werkzeug
      - typing-extensions>=3.7.4.3
      - ujson
      - web-compile
      - werkzeug>=1.0.0
